---
config:
  defaults:
    version: 1.0
    application_group: etl
    application_name: webscraper
    deployment_waittime: 30m
    jenkins_status_email: distribution.list@myorg.com
    region: us-west-2
    terraform_version: 1.0.0
  environment:
    defaults:
      foo: baz
      jenkins_status_email: env.distribution.list@myorg.com
    foo: bar
    prod:
      defaults:
        foo: andrew
      jenkins_status_email: prod.distribution.list@myorg.com
